name: Daily Program Generator

on:

  schedule:

    - cron: "30 14 * * *"

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      - name: Generate Program

        run: |

          python main.py

      - name: Commit Changes

        run: |

          git config user.name github-actions

          git config user.email actions@github.com

          git add .

          git commit -m "Daily program update" || exit 0

          git push